apiVersion: v1
kind: Secret
metadata:
  name: clean-review-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.global.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

